# The following line will download the latest Ubuntu Docker image
# to use as a foundation for building our own Docker image.
#FROM ubuntu:latest
#RUN apt-get update

# The following line will copy the syllabus.md file to the Docker container
# using the path that is specified second.
#COPY syllabus.md /syllabus.md

# The following line will download the latest Ubuntu Docker image
# to use as a foundation for building our own Docker image.
FROM ubuntu:latest
RUN apt-get update
#
# The following line will copy the day3.md file to the Docker container
# using the path that is specified second.
COPY day3.md /day3.md
